[pytest]
pythonpath = .
markers =
    smoke: marks tests related to smoke test
    register: marks tests related to user registration
    positive: marks tests related to positive test
    negative: marks tests related to negative test